### ISSUE TITLE
How do I determine the original fine name of an attachment?

### ISSUE THREAD

**Issue by woheme-c** [libyal/libpff#123]
Hello. 

I try to extract the name and type of each attachment file that is stored in the message. 

Do anybody know the method? Unfortunately I can´t find a proper way.

It would be very helfpful.

Greetings

**Comment by joachimmetz** [comment]
PST files are MAPI databases, find the corresponding MAPI values.

**Comment by woheme-c** [comment]
Hi Joachim.

Thanks for you answer.

Im sure that the information about the attachments is available. I can extract the type of the attachment (.pdf, .png, etc.) by using the magic-library. 

Even if I know that pst is a MAPI database, I still don't know the method of the pypff library that gives me the value. For example, when I iterate over the parts of the attachment, I can only read out the number of items, but it is not clear from the library how I can get the items or records themselves. Maybe I have some kind of an error in my thinking. With the "read_buffer" there is only the binary file of the file itself as far as I can see. I cannot read the filename from it. In any case, I can't find a method here either. Is there even this possibility of reading out the file types and file names in the library?

Greetings

**Comment by joachimmetz** [comment]
> I can extract the type of the attachment (.pdf, .png, etc.) by using the magic-library.

you mean mime type? that is necessary for encoding, file name is not required.

Note that pypff is WIP, per https://github.com/libyal/libpff/issues/2, closing issue.

**Comment by woheme-c** [comment]
I think you didnt get the question, unfortunately. 

every mime file carries information about type and also the name of the attachement. The question is, how to extract this informations. What is the method of the library with python.

 I allready extracted the type with the magic library because I didnt find the method with pypff. Same problem with the file-name.

greetings

**Comment by mhechthz** [comment]
Is there any new development in this question? Using the Python library I cannot figure out the name of the attachment. So I also used magic library but it is quite difficult to guess the type of the attachment. Furthermore I have to generate uui4 random names for the files to store it on disc. In the original E-Mail the name is always available, so should be stored somewhere in the message.

If there could be a method like `attachment.get_name()` it would be quite helpful. Or did I only miss the right way to get the name?

**Comment by rvpersie** [comment]
I've done a lot of research and unfortunately as it seems there is no way to extract the attachment name and the emails are written in .eml format, with magic library and mime-types module there is a way to re-create attachments and have them in included in an email, unfortunately not with their original name (so i use attachment_1, attachment_2 etc). Also due to this issue, it is also not possible to reconstruct emails to have in their text body images :(

**Comment by MathieuSeraphim** [comment]
Hello everyone,

After a bit of experimentation, I found a solution; and figured I'd share it to help fellow frustrated coders with their quest.

First, to get the attachments:
```
pst_filename = "path/to/your/file.pst"
pst_file = pypff.file()
pst_file.open(pst_filename)
root_folder = pst_file.get_root_folder()

for i in range(root_folder.get_number_of_sub_messages()):
    message = folder.get_sub_message(i)
    num_attachments = message.get_number_of_attachments()

    for j in range(num_attachments):
        attachment = message.get_attachment(j)
```

From there, you can get the attachment as binary data like this: `attachment_data = attachment.read_buffer(attachment.get_size())`
And, as others have stated, you can determine the file format using the magic library: `print(magic.from_buffer(attachment_data))`

This wasn't enough for me, as I needed the file name itself.
I figured out that you could get it through the entries within the attachment's record set entries.
From there, I identified that the entry of index 1 appeared to be the attachment name:
```
assert attachment.number_of_record_sets == 1  # Sanity check
record_set = attachment.get_record_set(0)
attachment_text = record_set.get_entry(1).get_data_as_string()
```
Which allowed me to properly extract and save the attachment data:
```
attachment_filename = join("path/to/save/directory", attachment_text)
with open(attachment_filename, "wb") as f:
    f.write(attachment_data)
```
This method worked for me accross different attachment formats, mostly JPEG and PDF files.

Note that the number of entries within the attachment's record set varies from one attachment to another (possibly based on the file type, but I didn't investigate further).
While the entry of index 1 was systematically the attachment filename in my case, I do not know why that is, and cannot guarantee that it will be the same for you as well.
Curiously, the entry of index 4 _usually_ was equal to the binary contents of `attachment_data`, as in `record_set.get_entry(4) == attachment.read_buffer(attachment.get_size())`.
But this wasn't always the case. Again, this could be due to the file type; but again, I didn't investigate further.

Anyway. Good luck in your endeavors!
