### ISSUE TITLE
Reading contacts from a pst file

### ISSUE THREAD

**Issue by datacycling** [libyal/libpff#98]
Thanks for creating this high performant library for parsing PST files.  Has anyone used this to extract contacts from a pst file ? If yes can you please share pointers.  Thanks.

**Comment by jengelh** [comment]
At the MAPI level, contacts are simply messages with PR_MESSAGE_CLASS=`IPM.Contact` and can be located in an arbitrary folder (though often one that is aptly named "Contacts" or so). They are represented in libpff with item type `LIBPFF_ITEM_TYPE_CONTACT`, since libpff parses PR_MESSAGE_CLASS as a convenience.
